sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 12
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
