# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine:
    image: ubuntu-2004:202201-02
    # Directory where steps will run. We use default "project" directory
    # to unify it for all jobiqo 8 projects
    working_directory: ~/project
    # Environment variables for all commands for easier control
    environment:
      VERSION_DOCKER_COMPOSE: 1.23.2
      VERSION_NVM: 0.34.0
      VERSION_NODE: 12.18.3
      VERSION_MKCERT: 1.4.1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm install"
      - run:
          name: update-npm
          command: "npm install -g npm@latest"
      - run: # run build
          name: build
          command: npm run build
      - run: # run tests
          name: test
          command: npm run test
